languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Chuwei's Homepage"
copyright = "&copy; 2025 Congo contributors"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["projects", "ideas"]
  description = ""

[params.author]
  name = "Chuwei Guo"
  image = "img/crop_chuwei.jpg"
  headline = "Guy Who's Really Into Robotics"
  bio = "Software engineer / project manager in the robotics field. Always eager to share about fun things I see or do. :robot:"
  links = [
    { linkedin = "https://www.linkedin.com/in/chuweiguo/" },
    { github = "https://github.com/ChuweyBar" },
    { youtube = "https://www.youtube.com/@chuweiguo9475" },
    { email = "mailto:chuwei0807@gmail.com" },
  ]
