baseURL = "https://chuweybar.github.io/"

languageCode = "en"
languageName = "English (Australia)"
languageDirection = "ltr"
weight = 1

title = "My awesome website"

[params.author]
name = "Chuwei Guo"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { twitter = "https://twitter.com/username" }
]

colorScheme = "congo"
theme = "congo"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true
